name: uni_links
description: Flutter plugin for accepting incoming links - App/Deep Links (Android), Universal Links and Custom URL schemes (iOS).
version: 0.5.0
homepage: https://github.com/avioli/uni_links/tree/master/uni_links

publish_to: 'none'

dependencies:
  flutter:
    sdk: flutter
  uni_links_platform_interface:
    path: ../uni_links_platform_interface/
  uni_links_web:
    path: ../uni_links_web/

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.11.0

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.1 <3.0.0"

flutter:
  plugin:
    platforms:
      android:
        package: name.avioli.unilinks
        pluginClass: UniLinksPlugin
      ios:
        pluginClass: UniLinksPlugin
