name: uni_links_web
description: A web implementation of the Uni Links platform interface.
version: 0.1.0
homepage: https://github.com/avioli/uni_links/tree/master/uni_links_web
publish_to: 'none'
dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  uni_links_platform_interface:
    git:
      url: https://github.com/sertifier/uni_links
      ref: master
      path: uni_links_platform_interface

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.11.0

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.1 <3.0.0"

flutter:
  plugin:
    platforms:
      web:
        pluginClass: UniLinksPlugin
        fileName: 'uni_links_web.dart'
